- app-dev/cloud-functions-2ndgen-what-are-coldstarts/.gcloudignore
- app-dev/cloud-functions-2ndgen-what-are-coldstarts/deploy.sh
- app-dev/cloud-functions-2ndgen-what-are-coldstarts/index.js
- app-dev/cloud-functions-2ndgen-what-are-coldstarts/package.json
- app-dev/cloud-functions-2ndgen-what-are-coldstarts/readme.md
WIP bc I still need to add the images of the logs that illustrate the various states. Wanted to share my work sooner rather than later.
> adding cloud functions demo on visualizing cold starts, warm instances, and global scope optimizations

- ai-ml/vertex-ai-pipelines-template-blog/google_cloud_pipeline_template.ipynb
Adding a Notebook to the ai-ml folder. Some more context on the Notebook:
- Notebook is part of a blogpost. 
- This Notebook has been reviewed. 
- This notebook will also be added to the official Vertex AI samples repo.
> Adding google_cloud_pipeline_template noteook to AI folder

- ai-ml/vertex-ai-first-model-in-production/vertex-ai-first-model-deployed.ipynb
Adding a Notebook that shows how to get your first model in productions using Vertex AI and BigQuery.
> adding first model deployed notebook

- data-analytics/next-2022-workshop/dataproc-serverless/citibike.py
Publishing code here for a workshop taking place at NEXT
> adding citibike code for next 2022 workshop

- app-dev/github-actions-wif-cloudrun/README.md
- app-dev/github-actions-wif-cloudrun/main.tf
Tested in https://github.com/glasnt/glowing-octo-meme,  glasnt-appdevrepro-2194, https://boo-xpezxp7ikq-uc.a.run.app
> Add tutorial for WIF + Cloud Run + GitHub Actions

- app-dev/github-actions-wif-cloudrun/README.md
With thanks to @simonw for the feedback!
> Clarify prereqs, smol cleanup

- app-dev/github-actions-wif-cloudrun/README.walkthrough.md
- app-dev/github-actions-wif-cloudrun/automate.sh
- app-dev/github-actions-wif-cloudrun/main.tf
There's some sort of race conditions here, but this cleans up most of it.
> Update github wif

- ai-ml/vertex-ai-first-model-in-production/vertex-ai-first-model-deployed.ipynb
- Updating 'first model in production' notebook with some minor fixes. 
- Updated the documentation.
> updating first model in production notebook with fixes

- ai-ml/vertex-ai-first-model-in-production/vertex-ai-first-model-deployed.ipynb
Fixed a minor bug in the notebook on BQML and Vertex AI.
> fixing a bug

- data-analytics/beam_ml_toxicity_in_gaming/LICENSE
- data-analytics/beam_ml_toxicity_in_gaming/README.md
- data-analytics/beam_ml_toxicity_in_gaming/toxicity_pipeline.py
Toxicity beam ML demo pipeline code
> Initial commit of toxicity Beam ML pipeline

- app-dev/cloud-quiz/app/page.tsx
- the app was showing signout button even when not logged in
> fix sign in bug for quiz app

- app-dev/cloud-quiz/app/components/sign-in-button.tsx
enable anonymous auth
change ui to represent anonymous auth
> remove google auth

- data-analytics/beam_ml_toxicity_in_gaming/exercises/LICENSE
- data-analytics/beam_ml_toxicity_in_gaming/exercises/README.md
- data-analytics/beam_ml_toxicity_in_gaming/exercises/part1.py
- data-analytics/beam_ml_toxicity_in_gaming/exercises/part2.py
- data-analytics/beam_ml_toxicity_in_gaming/exercises/requirements.txt
- data-analytics/beam_ml_toxicity_in_gaming/exercises/toxicity_pipeline.py
This PR creates exercise starter files from [data-analytics/beam_ml_toxicity_in_gaming](https://github.com/GoogleCloudPlatform/devrel-demos/tree/main/data-analytics/beam_ml_toxicity_in_gaming).
TODO comments prompt the student who follows along with the lab.
> Create exercise files for data-analytics/beam_ml_toxicity_in_gaming

- app-dev/cloud-quiz/app/components/question-panel.tsx
- app-dev/cloud-quiz/app/components/reveal-answers-button.tsx
- app-dev/cloud-quiz/app/components/sign-out-button.tsx
- app-dev/cloud-quiz/app/components/submit-answer-button.tsx
- app-dev/cloud-quiz/app/page.tsx
- Question panel now looks like a panel
- Clarified missed right answers
- Buttons are pleasant
- Margins are reasonable
- Divs are padded
- Questions are larger
> feat: it's beautiful

- app-dev/cloud-quiz/.gitignore
- app-dev/cloud-quiz/infra/.gitignore
- app-dev/cloud-quiz/infra/README.md
- app-dev/cloud-quiz/infra/apis.tf
- app-dev/cloud-quiz/infra/main.tf
- app-dev/cloud-quiz/infra/outputs.tf
- app-dev/cloud-quiz/infra/terraform.tfvars.sample
- app-dev/cloud-quiz/infra/variables.tf
- app-dev/cloud-quiz/infra/versions.tf
This creates infrastructure in a blank project
for:
* Cloud Run APIs
* Enabling Secret Manager
* Installing a Firestore instance.
> [Cloud Quiz] Terraform for initial infrastructure setup

- data-analytics/beam_ml_toxicity_in_gaming/part2.py
- data-analytics/beam_ml_toxicity_in_gaming/toxicity_pipeline.py
Updating the parameters to match
> fixing the arguments

- other/train-to-cloud-city/app/server/main.py
- other/train-to-cloud-city/app/server/train_types.py
* Adding new missions
* Additional changes from linter
> refactor: updating train patterns / missions

- data-analytics/data-dash/webapp/main.py
> feat: updates

- other/train-to-cloud-city/devices/signal/CIRCUITPY/boot.py
- other/train-to-cloud-city/devices/signal/CIRCUITPY/code.py
- other/train-to-cloud-city/devices/signal/CIRCUITPY/id.txt
- other/train-to-cloud-city/devices/signal/README.md
Firmware for the train signals.
> train demo - firmware for signals

- devops/inter-org-artifacts-release/App.py
- devops/inter-org-artifacts-release/Dockerfile
- devops/inter-org-artifacts-release/Imagerelease.tf
- devops/inter-org-artifacts-release/README.md
- devops/inter-org-artifacts-release/copy_image.py
**Change List**
1. Added a folder 'inter-org-artifacts-release' under devops sub folder.
2. 5 files under the folder: App.py, copy_image.py, Dockerfile, Imagerelease.tf and README.md
Ref. to unpublished blog post:
https://docs.google.com/document/d/1s7MdYgypO6o7H9k6EKAwjHA1xvk7uWzsJXZIZx3rWDY/edit?tab=t.0#heading=h.7fzqzo30q1u2
> folder + files for interorg artifacts release blog

- data-analytics/minigolf-demo/bq_notebook.ipynb
- data-analytics/minigolf-demo/helper.py
- data-analytics/minigolf-demo/image_recognition.py
- data-analytics/minigolf-demo/upload.py
This PR is updating Golf with Gemini to simplify recording/uploading process and change variable names.
> Fixing Minigolf

- devops/inter-org-artifacts-release/README.md
Updated README.md with the actual link to the published post.
> Updated README.md

- ai-ml/gemini-chatbot-app/.gitignore
- ai-ml/gemini-chatbot-app/LICENSE
- ai-ml/gemini-chatbot-app/README.md
- ai-ml/gemini-chatbot-app/lesson01/Procfile
- ai-ml/gemini-chatbot-app/lesson01/deploy.sh
- ai-ml/gemini-chatbot-app/lesson01/requirements.txt
- ai-ml/gemini-chatbot-app/lesson01/streamlit_app.py
- ai-ml/gemini-chatbot-app/lesson02/Procfile
- ai-ml/gemini-chatbot-app/lesson02/deploy.sh
- ai-ml/gemini-chatbot-app/lesson02/llm.py
- ai-ml/gemini-chatbot-app/lesson02/requirements.txt
- ai-ml/gemini-chatbot-app/lesson02/streamlit_app.py
App uses Streamlit, Gemini Flash 1.5 & Cloud Run.
> feat(AI/AML App): Add Gemini Chat bot - sample applicaiton

- devops/otel-trace-exemplar/otelcol/Dockerfile
- devops/otel-trace-exemplar/recursive/Dockerfile
- devops/otel-trace-exemplar/recursive/go.mod
> nit(devops): update Go and OpenTelemetry Collector versions for trace exemplar sample

- ai-ml/gemini-chatbot-app/lesson02/llm.py
> Chore: code cleanup

- ai-ml/gemini-multimodal/practical_multimodal_use_cases_with_gemini.ipynb
Another attempt to correct the link
> fix: correct the link again

- ai-ml/deep-learning-ai-gemini/L5_videos.ipynb
Adding a folder to store notebooks on Gemini
> adding deep learning AI course notebook

- infrastructure/movie-search-app/.gitignore
- infrastructure/movie-search-app/Procfile
- infrastructure/movie-search-app/README.md
- infrastructure/movie-search-app/connect_tcp.py
- infrastructure/movie-search-app/data_model.py
- infrastructure/movie-search-app/gemini_model.py
- infrastructure/movie-search-app/movie_search.py
- infrastructure/movie-search-app/pinecone_model.py
- infrastructure/movie-search-app/requirements.txt
feat: new sample application for Pinecone and PostgreSQL backend
> feat: movie search sample app with Pinecone and PostgreSQL backend

- infrastructure/movie-search-app/README.md
fix: corrected documentation commands for cloud run deployment
> fix: corrected documentation commands for cloud run deployment

- infrastructure/cymbal-store-embeddings/README.md
docs: fixed README repository path
> docs: fixed README repository path

- infrastructure/alloydb-scale-function/go-sample/.gitignore
- infrastructure/alloydb-scale-function/go-sample/alloydbscale.go
feat: add alloydb scale up and down example using go
> feat: add alloydb scale up and down example using go

- infrastructure/cymbal-store-embeddings/data_model.py
- infrastructure/movie-search-app/gemini_model.py
- infrastructure/movie-search-app/pinecone_model.py
feat: fix model output formatting and add license header to a script
> feat: fix model output formatting

- infrastructure/movie-search-app/README.md
- infrastructure/movie-search-app/movie_search.py
- infrastructure/movie-search-app/pinecone_model.py
Updated code to reflect new pinecone API, changed table definition for postgres and corrected README
> feat: new pinecone API

- infrastructure/movie-search-app/README.md
Adding instructions for Cloud Run deployments
> fix: add more information to readme acccordign to issue #290

- infrastructure/cymbal-store-embeddings/README.md
- infrastructure/cymbal-store-embeddings/cymbal_store.py
- infrastructure/cymbal-store-embeddings/gemini_model.py
fix: fixed gemini model calls, readme and chat interface bug 446197056
> fix: fixed gemini model calls, readme and chat interface
